/**
 * 
 */
package edu.caltech.networksimulator;

/**
 * @author Carly
 *
 * Flows represent active connections.
 * Flows will have source and destination addresses; packets generated by each
 * flow will have the same destination address, to ensure they are routed correctly.
 * 
 * Flows have a source and destination address, and generate packets at a rate
 * controlled by the congestion control algorithm defined for that flow. You
 * should implement at least two different congestion control algorithms, e.g.
 * TCP Reno and FAST-TCP, and be able to choose independently between them for
 * each flow. Flows may send a continuous stream of data, or may send a finite
 * user-specifiable amount of data; they may also start immediately or after some
 * user-specifiable delay.
 */
public class Flow {
	
	private static final String ctrl_alg = "TCP Reno"; // for example
	// probably want src as a networkComponent
	private final long src, dest;
	private final int _id;
	private final long data_size;
	private final long start_delay;
	
	/**
	 * @param src The source IP
	 * @param dest The destination IP
	 * @param _id The ID number of the flow
	 * @param data_size The amount of data to send as part of this flow, in MB (?)
	 * @param start_delay The delay in starting to send this flow (milliseconds)
	 */
	public Flow(long src, long dest, int _id, long data_size, long start_delay) {
		this.src = src;
		this.dest = dest;
		this._id = _id;
		this.data_size = data_size;
		this.start_delay = start_delay;
	}
	
//	public Packet getPacket() {
//		//return new Packet(this.src, this.dest);
//	}

}
